// model.cpp
//
// Template for embedding a quantized TensorFlow Lite model
// into an ESP32-S3 firmware project.
//
// After training your model, convert it to a .tflite file,
// then run:
//
//     xxd -i your_model.tflite > model_raw.cc
//
// Then copy the array contents into g_model[] below,
// and set g_model_len accordingly.

#include <cstdint>
#include "model.h"

// -----------------------------------------------------------------------------
// Placeholder model data
// Replace this with the actual contents generated by xxd -i
// -----------------------------------------------------------------------------

// Example placeholder (empty model)
const unsigned char g_model[] = {
    // Replace with: xxd -i your_model.tflite
    0x20, 0x00, 0x00, 0x00  // minimal placeholder so the linker is happy
};

// Actual length of the model array above
const int g_model_len = sizeof(g_model);
